In [1]:
import numpy as np
from scipy import stats

from statistics import mean
import itertools as itt

# Use the following code for the questions below:

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
len(a)

12

In [2]:
# 1 
# How many negative numbers are there?
ab = sum(a < 0)
ab

4

In [3]:
# 2 
# How many positive numbers are there?

ac = sum(a > 0)
ac

5

In [4]:
# 3
# How many even positive numbers are there?

ad = a[(a > 0) & (a % 2 == 0)]
ad

len(ad)



3

In [5]:
# 4
# If you were to add 3 to each data point, how many positive numbers would there be?

ae = np.array(a + 3)
ae

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [6]:
# 5
# If you squared each number, what would the new mean and standard deviation be?

af = np.array(a ** 2)
af


array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [7]:
af.mean(), round(af.std(), 4)

(74.0, 144.0243)

In [8]:
# 6
# A common statistical operation on a dataset is centering. This means to adjust the data such that 
# the mean of the data is 0. This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.



center_function = lambda x: x - x.mean()
data_centered = center_function(a)
print(data_centered)
a.mean()

data_centered.mean()

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


0.0

In [9]:
# 7 
# Calculate the z-score for each data point. 

ag = stats.zscore(a, axis=None)
ag

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [10]:
# 8


## Setup 1
aq = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use Python's built-in functionality/operators to determine the following


In [11]:
## Setup 1
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(aq)
sum_of_a

55

In [12]:
## Setup 1
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(aq)
min_of_a

1

In [13]:
## Setup 1
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(aq)
max_of_a

10

In [14]:
## Setup 1
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = mean(aq)
mean_of_a

5.5

In [15]:
## Setup 1
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all 
#  the numbers in the above list together

product_of_a = np.prod(aq)
product_of_a
   

3628800

In [16]:
## Setup 1
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared 
# like [1, 4, 9, 16, 25...]
squares_of_a = a ** 2
squares_of_a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [17]:
## Setup 1
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

def odds_in_a(aq):
    aq = np.array(aq)
    return aq[aq % 2 == 1]

odd = odds_in_a(aq)
odd



array([1, 3, 5, 7, 9])

In [18]:
## Setup 1
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

## evens_in_a = (a % 2 == 0)
## evens_in_a

## this above is a boolean T / F list


# this returns the evens :

def evens_in_a(aq):
    aq = np.array(aq)
    return aq[aq % 2 == 0]

even = evens_in_a(aq)
even

array([ 2,  4,  6,  8, 10])

In [19]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...


In [32]:
## Setup 2

## Consider what it would take to find the sum, min, max, average, sum, product, and list 
## of squares for this list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
    ]

## turning b into an array : 
bb = np.array(b)
bb

array([[3, 4, 5],
       [6, 7, 8]])

In [33]:
## Setup 2
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
    ## **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [31]:
sum_of_b2 = bb.sum()
sum_of_b2

NameError: name 'bb' is not defined

In [23]:
## Setup 2
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b

3

In [24]:
min_of_b2 = bb.min()
min_of_b2

3

In [25]:
## Setup 2
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [26]:
max_of_b2 = bb.max()
max_of_b2

8

In [27]:
## Setup 2
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b 


5.5

In [28]:
mean_of_b2 = bb.mean()
mean_of_b2

5.5

In [29]:
## Setup 2
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

product_of_b

20160

In [30]:
product_of_b2 = np.prod(bb)
product_of_b2

20160

In [31]:
## Setup 2
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [32]:
squares_of_b2 = bb ** 2
squares_of_b2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [33]:
## Setup 2
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

odds_in_b

[3, 5, 7]

In [34]:
odds_in_b2 = np.array([bb])
bb[bb % 2 == 1]

array([3, 5, 7])

In [35]:
## Setup 2
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [36]:
evens_in_b2 = np.array([bb])
bb[bb % 2 == 0]

array([4, 6, 8])

In [42]:
## Setup 2
# Exercise 9 - print out the shape of the array b.

np.array(bb).shape

(2, 3)

In [43]:
## Setup 2
# Exercise 10 - transpose the array b.
transposition = np.array(bb)
print(transposition.T)

[[3 6]
 [4 7]
 [5 8]]


In [47]:
## Setup 2
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
newbb = bb.reshape(1,6)
newbb

array([[3, 4, 5, 6, 7, 8]])

In [49]:
## Setup 2
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

newestbb = bb.reshape(6,1)
newestbb

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [3]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array before using numpy array methods.

cc = np.array(c)
cc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
## Setup 3
# Exercise 1 - Find the min, max, sum, and product of c.
cd = cc.min(), cc.max(), cc.sum(), cc.prod()
cd


(1, 9, 45, 362880)

In [10]:
## Setup 3
# Exercise 2 - Determine the standard deviation of c.

ce = round(cc.std(), 5)
ce

2.58199

In [11]:
## Setup 3
# Exercise 3 - Determine the variance of c.

cf = np.var(cc)
cf

6.666666666666667

In [12]:
## Setup 3
# Exercise 4 - Print out the shape of the array c

np.shape(cc)

(3, 3)

In [22]:
## Setup 3
# Exercise 5 - Transpose c and print out transposed result.

#transposition = np.array(bb)
#print(transposition.T)

#transposition = np.array(cc)
#transposition.T

cg = cc.T
cg

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
## Setup 3
# Exercise 6 - Get the dot product of the array c with c. 

ch = np.dot(cc,cc)
ch


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [45]:
## Setup 3
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

ci = np.sum(cc * cg)
ci

261

In [46]:
## Setup 3
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.

cj = np.prod(cc * cg)
cj


131681894400

In [48]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

dd = np.array(d)
dd

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [52]:
## Setup 4
# Exercise 1 - Find the sine of all the numbers in d

de = np.sin(dd)
de

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [53]:
## Setup 4
# Exercise 2 - Find the cosine of all the numbers in d

df = np.cos(dd)
df


array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [54]:
## Setup 4
# Exercise 3 - Find the tangent of all the numbers in d

dg = np.tan(dd)
dg

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [56]:
## Setup 4
# Exercise 4 - Find all the negative numbers in d

dh = (dd < 0)
dh


array([[False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False,  True, False,  True, False]])

In [60]:
## Setup 4
# Exercise 5 - Find all the positive numbers in d


di = (dd >= 0)
di

array([[ True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True,  True, False,  True, False,  True]])

In [62]:
## Setup 4
# Exercise 6 - Return an array of only the unique numbers in d.

dj = np.unique(dd)
dj

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [70]:
## Setup 4
# Exercise 7 - Determine how many unique numbers there are in d.

dk = len(np.unique(dd))
dk

11

In [73]:
## Setup 4
# Exercise 8 - Print out the shape of d.

dl = np.shape(dd)
dl

(3, 6)

In [75]:
## Setup 4
# Exercise 9 - Transpose and then print out the shape of d.

dm1 = dd.T
dm1

dm2 = np.shape(dm1)
dm2

(6, 3)

In [76]:
## Setup 4
# Exercise 10 - Reshape d into an array of 9 x 2

newdd = dd.reshape(9,2)
newdd

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])